dist: xenial
language: python
python: 3.7.2
install:
  - pip install -r requirements.txt
script:
  - cd breaking_brain/
  - ./manage.py test
  - cd ..
  - black --diff --check -l 79 -S breaking_brain/ > black_report.txt

